augment_test: false
augment_training: true  # whether to augment the training data by rotating
batch_size: 32
chip_number: 10773
epochs: 100
in_channels: 38 # 35 bands in the predictor variables, 5 features multiplied by 7 bands; 38, including the elevation, slope and aspect
learning_rate: 0.001
loss_function_flag: focal_loss  # focal_loss, cross_entropy (classification task), MSE loss (regression task)
num_classes: 2  # 101 classes in the target variable, [0, 100], 2 classes in the binary classification, change to 1 when conducting the regression task
num_workers: 1
prefetch_factor: 2
shuffle_test: false # whether to shuffle the test data
shuffle_training: true  # whether to shuffle the training data
split: 0.9  # 90% training, 10% testing
training_sample_folder: training_sample_conus_v2
training_sample_x_label_folder: x_training_topography
training_sample_y_label_folder: y_label_binary # y_label for the regression task, y_label_binary for the classification task
training_version: binary_classification_v6_conus_topography
exclude_ccap: True  # whether to exclude the CCAP data
